### ISSUE TITLE
Example links 404

### ISSUE THREAD

**Issue by boydgreenfield** [nteract/examples#19]
Hi folks – awesome project (and we're exploring using it to replace the Jupyter notebook interfaces in our microbial genomics platform)!

I wanted to flag that the example links all seem to 404 on Binder (as of 1/21/19). After clicking about the view a bit, I can get to [a version that'll render in Binder](https://mybinder.org/v2/gh/nteract/examples/master?filepath=happiness.ipynb), but it's doing so in a vanilla Jupyter notebook.

Didn't have a chance to dig in much further, but hopefully it's either a temporary issue or a simple URL change. 🤞

**Comment by rs2** [comment]
1. The `/nteract` route is not available once demo links are launched. See [binder docs](https://mybinder.readthedocs.io/en/latest/howto/user_interface.html#nteract) for details.
1. See [example project](https://github.com/norvig/pytudes/blob/master/requirements.txt) that has `nteract` [available in binder](https://mybinder.org/v2/gh/norvig/pytudes/master?urlpath=nteract/tree/ipynb).

**Comment by rs2** [comment]
See #23
