### ISSUE TITLE
Binder failed to build

### ISSUE THREAD

**Issue by choldgraf** [nteract/examples#21]
I just tried building Binder and it gave this error on build:

![image](https://user-images.githubusercontent.com/1839645/52523285-a2aa9f80-2c44-11e9-97b4-c983a48f0e7f.png)

just FYI!

**Comment by betatim** [comment]
The fix for this is in https://github.com/jupyter/repo2docker/pull/576. The problem is that repo2docker isn't succeeding in pinning the version of conda used and the latest release of conda contains a but (trying to build in `/srv/condafoobar` instead of /srv/conda/foobar`).

**Comment by choldgraf** [comment]
hmmm, so now the examples repository builds but I'm getting the 404 error again, so maybe the original problem wasn't fixed?

**Comment by betatim** [comment]
What is "the 404 error"? Do you think it is a problem with repo2docker or the repo itself?

**Comment by choldgraf** [comment]
Ah sorry, I meant the 404 error that originally sparked this issue, but I realized it was actually originally in the repo2docker repo here:

https://github.com/jupyter/repo2docker/issues/570

Here's a Binder link that results in a 404 for me upon redirect:

https://mybinder.org/v2/gh/nteract/examples/master?urlpath=%2Fnteract%2Fedit%2Fpython%2Fintro.ipynb

**Comment by choldgraf** [comment]
ok I think nteract is working again - I just tried w/ the nteract-examples repository and that worked! Closing now but feel free to open if something is still wrong!
